server:
  port: 8085

spring:
  logging:
    level : debug
  datasource:
    url: jdbc:postgresql://185.8.173.130:5432/vehicle_db
    driver-class-name: org.postgresql.Driver
    username: vehicle_user
    password: Qmars@0109
  jpa:
    hibernate:
      ddl-auto: none
      debug: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true